# Generated by Django 2.0.5 on 2018-05-28 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='DayResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('income', models.IntegerField()),
                ('day_num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Duty_setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_num', models.IntegerField(default=1)),
                ('day_name', models.CharField(max_length=30)),
                ('avg_income', models.IntegerField(default=1)),
                ('worked_hours_in_day', models.IntegerField(default=8)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameSkill', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Skills_limits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum_employee', models.IntegerField()),
                ('name_skill', models.CharField(default='<django.db.models.fields.related.ForeignKey>', max_length=30)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rasp.Skill')),
            ],
        ),
        migrations.CreateModel(
            name='UserDayResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_point_rating', models.IntegerField(default=0)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rasp.DayResults')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rasp.Skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WeekendSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekendsPerWeek', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='rating',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rasp.Skill'),
        ),
        migrations.AddField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='duty_setting',
            name='skills_per_day',
            field=models.ManyToManyField(to='rasp.Skills_limits'),
        ),
    ]
