# Generated by Django 2.0.4 on 2018-04-30 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rasp', '0003_auto_20180430_0945'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeekendSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekendsPerWeek', models.IntegerField()),
            ],
        ),
    ]


[4,6,7,8,9,53,52]
j = 4
j = 6

i = 0
i = 1