# Generated by Django 2.0.5 on 2018-05-14 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rasp', '0008_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameSkill', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='personalvotes',
            name='skills',
            field=models.ManyToManyField(to='rasp.Skill'),
        ),
    ]
