# Generated by Django 2.0.5 on 2018-05-14 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rasp', '0010_auto_20180514_1755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daysoff',
            name='skills_per_day',
        ),
        migrations.AddField(
            model_name='daysoff',
            name='skills_per_day',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rasp.SkillPerDay'),
        ),
        migrations.RemoveField(
            model_name='personalvotes',
            name='skills',
        ),
        migrations.AddField(
            model_name='personalvotes',
            name='skills',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rasp.Skill'),
        ),
    ]
