# Generated by Django 2.0.5 on 2018-05-14 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rasp', '0011_auto_20180514_1806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daysoff',
            name='skills_per_day',
        ),
        migrations.AddField(
            model_name='daysoff',
            name='skills_per_day',
            field=models.ManyToManyField(to='rasp.SkillPerDay'),
        ),
    ]
