# Generated by Django 2.0.4 on 2018-04-30 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rasp', '0002_daysoff_weekendsperweek'),
    ]

    operations = [
        migrations.RenameField(
            model_name='daysoff',
            old_name='weekendsPerWeek',
            new_name='employeeInDay',
        ),
    ]
