# Generated by Django 2.0.4 on 2018-05-05 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rasp', '0006_auto_20180505_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weekendsetting',
            name='weekendsPerWeek',
            field=models.IntegerField(),
        ),
    ]
